DROP TABLE IF EXISTS TBL_CATEGORY;
CREATE TABLE TBL_CATEGORY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(45) NOT NULL,
    description VARCHAR(200) NOT NULL
);
-- DROP TABLE IF EXISTS TBL_EMPLOYEES;
  
-- CREATE TABLE TBL_EMPLOYEES (
--   id INT AUTO_INCREMENT  PRIMARY KEY,
--   first_name VARCHAR(250) NOT NULL,
--   last_name VARCHAR(250) NOT NULL,
--   email VARCHAR(250) DEFAULT NULL
-- );
DROP TABLE IF EXISTS TBL_PRODUCT;
CREATE TABLE TBL_PRODUCT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(45) NOT NULL,
    description VARCHAR(200) NOT NULL,
    price VARCHAR(45) NOT NULL,
    image_url VARCHAR(45) NOT NULL,
    category_id INT NOT NULL,

    FOREIGN KEY(category_id) REFERENCES TBL_CATEGORY
    -- CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (category_id)
    -- REFERENCES TBL_CATEGORY (id)

);